# runtime: nodejs
# env: flex

# manual_scaling:
#   instances: 1

# service: savorlink-web-dev

runtime: nodejs
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: .18
  disk_size_gb: 10

handlers:
- url: /.*
  script: server.js
  secure: never
