export const COMMON_SUBMITFEEDBACK_START = 'COMMON_SUBMITFEEDBACK_START';
export const COMMON_SUBMITFEEDBACK_SUCCESS = 'COMMON_SUBMITFEEDBACK_SUCCESS';
export const COMMON_SUBMITFEEDBACK_ERROR = 'COMMON_SUBMITFEEDBACK_ERROR';

